spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.134:3306/yutest?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1qaz@WSX
  session:
    store-type: REDIS
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 192.168.100.229
    password: cplh1234

#security:
  #basic:
    #enabled: false
yu:
  security:
    browser:
      loginPage: /demo-login.html
      loginType: JSON
      rememberMeSeconds: 60
      signOutUrl: /demo-logout.html
    #code:
      #image:
        #urls: /api/user
    social:
      filterProcessesUrl: /login
      qq:
        appId: 101858876
        appSecret: f0d7402da2b4ccbbf35abe073a347f7f
        providerId: qq
      weixin:
        appId: wxa6748bb1ed65022e
        appSecret: f7d4745253a499f49e243c4673fe1d81
        providerId: weixin
server:
  port: 8080
  session:
    timeout: 60
security:
  oauth2:
    client:
      client-id: yu
      client-secret: yusecret