spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.134:3306/yutest?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1qaz@WSX
  session:
    store-type: none
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#security:
  #basic:
    #enabled: false
yu:
  security:
    browser:
      loginPage: /demo-login.html
      loginType: JSON
      rememberMeSeconds: 60
    #code:
      #image:
        #urls: /api/user
    social:
      qq:
        appId: 101854065
        appSecret: 5c6ca8cdd129e3c3612f0a3aeeb224e3
        providerId: callBack
      filterProcessesUrl: /qqLogin
server:
  port: 80